---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
    - name: Install xerver packages and other requirements
      package:
        name:
          - gpg-agent
          - xorg
          - xserver-xorg-input-evdev
          - xserver-xorg-input-all
        state: present
  tasks:
    - name: "Include kilip.regolith"
      include_role:
        name: "kilip.regolith"
